### ISSUE TITLE
ImportError: cannot import name 'ParallelRenderer' from 'threednel.renderer.parallel'

### ISSUE THREAD

**Issue by kirawursthorn** [google-deepmind/threednel#2]
Hi!
I am trying to set up 3DNEL using the instructions for docker. Everything works just fine with no modifications at all until `pose_estimation.py` is run and it throws following exception because the class `ParallelRenderer` is missing:
```shell
Traceback (most recent call last):
  File "/root/threednel/scripts/pose_estimation.py", line 25, in <module>
    from threednel.bop.data import BOPTestDataset, RGBDImage
  File "/root/threednel/threednel/bop/data.py", line 30, in <module>
    from threednel.renderer.parallel import ParallelRenderer
ImportError: cannot import name 'ParallelRenderer' from 'threednel.renderer.parallel' (/root/threednel/threednel/renderer/parallel.py)
```
My best guess is pararender has to be integrated here in some way but I not sure how. Could you provide some instructions?

**Comment by StannisZhou** [comment]
Hi Kira, thanks for raising the issue. It seems this is because I accidentally deleted the renderer wrapper code in the final cleanups before release. I added the missing code. Just tested it on my end and it should be working now.

I am closing the issue for now but feel free to reopen if you run into additional issues.
